### ISSUE TITLE
Geopandas dies during intersection

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#32]
When geopandas tried to use rtree it died due to
```python
>>> import rtree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/home/user22/.local/lib/python3.6/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/mnt/home/user22/.local/lib/python3.6/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/mnt/home/user22/.local/lib/python3.6/site-packages/rtree/core.py", line 125, in <module>
    raise OSError("Could not find libspatialindex_c library file")
OSError: Could not find libspatialindex_c library file
```

Geopandas depends on rtree which depends on libspatialindex.

**Comment by sverhoeven** [comment]
As root manually ran `apt install libspatialindex-c4v5` fixes the exception. 
Needs to be included into Ansible
